CREATE TABLE if not exists `Product` (
  `sku_id` varchar(8) NOT NULL,
  `image` varchar(300) DEFAULT NULL COMMENT 'Points to S3',
  `additional_image_link` varchar(2048) DEFAULT NULL,
  `style_id` varchar(128) DEFAULT NULL,
  `class_id` varchar(128) DEFAULT NULL,
  `color` varchar(128) DEFAULT NULL,
  `color_code` varchar(128) DEFAULT NULL,
  `color_family` varchar(128) DEFAULT NULL,
  `size` varchar(128) DEFAULT NULL,
  `size_id` varchar(128) DEFAULT NULL,
  `department_id` varchar(128) DEFAULT NULL,
  `dissection-code` varchar(128) DEFAULT NULL,
  `hazmat` boolean DEFAULT NULL,
  `redline` boolean DEFAULT NULL,
  `promoted` boolean DEFAULT NULL,
  `tax_code` varchar(128) DEFAULT NULL,
  `vendor` varchar(128) DEFAULT NULL,
  `list_price` decimal(6,2) DEFAULT NULL,
  `sale_price` varchar(128) DEFAULT NULL,
  `sale_price_effective_date` varchar(200) DEFAULT NULL,
  `currency` varchar(3) DEFAULT NULL,
  `shoprunner_eligible` boolean DEFAULT NULL,
  `title` varchar(200) DEFAULT NULL,
  `link` varchar(2084) DEFAULT NULL,
  `prod_description` varchar(4096) DEFAULT NULL,
  `start_date` timestamp DEFAULT NULL,
  `featured_color` boolean DEFAULT NULL,
  `featured_color_category` varchar(256) DEFAULT NULL,
  `related_products` varchar(256) DEFAULT NULL,
  `pre_order` boolean DEFAULT NULL,
  `handling_code` varchar(128) DEFAULT NULL,
  `video` varchar(64) DEFAULT NULL,
  `proportion` varchar(128) DEFAULT NULL,
  `proportion_products` varchar(64) DEFAULT NULL,
  `master_style` varchar(64) DEFAULT NULL,
  `cannot_return` boolean DEFAULT NULL,
  `great_find` boolean DEFAULT NULL,
  `web_exclusive` boolean DEFAULT NULL,
  `ny_deals` boolean DEFAULT NULL,
  `promo_tagline` varchar(64) DEFAULT NULL,
  `partially_promoted` boolean DEFAULT NULL,
  `product_category` varchar(1024) DEFAULT NULL,
  `sort_order` varchar(128) DEFAULT NULL,
  `quantity_sold` int DEFAULT NULL,
  `average_rating` float(4) DEFAULT NULL,
  PRIMARY KEY (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;